// agents/park/venues.js — static data for all 30 MLB stadiums.
//
// Key fields:
//   lat, lng                  — for OpenWeather API lookups
//   altitude_feet             — Coors effect driver
//   orientation_degrees       — direction the stadium "faces" (home plate -> CF)
//                               Used to rotate wind_bearing into relative wind.
//   roof_type                 — open|retractable|dome; dome disables weather
//   surface                   — grass|turf
//   dims_*                    — outfield distances in feet
//   run_factor / hr_factor    — classic park factors (3-yr rolling)
//   f5_factor                 — our internal F5-specific park factor, updated
//                               seasonally from MLBIE's own outcomes table.
//
// Values are sourced from public park-factor databases (ESPN Stats & Info,
// Fangraphs Guts!, Statcast). Update annually; this is a baseline snapshot.

export const VENUES = [
  {
    id: '1',
    name: 'Angel Stadium',
    team: 'LAA',
    city: 'Anaheim',
    lat: 33.80029,
    lng: -117.8827,
    altitude_feet: 150,
    orientation_degrees: 40,
    roof_type: 'open',
    surface: 'grass',
    lf_line_feet: 330,
    rf_line_feet: 330,
    cf_feet: 396,
    run_factor: 0.97,
    hr_factor: 1.00,
    f5_factor: 0.97,
  },
  {
    id: '2',
    name: 'Minute Maid Park',
    team: 'HOU',
    city: 'Houston',
    lat: 29.75725,
    lng: -95.35552,
    altitude_feet: 43,
    orientation_degrees: 345,
    roof_type: 'retractable',
    surface: 'grass',
    lf_line_feet: 315,
    rf_line_feet: 326,
    cf_feet: 409,
    run_factor: 1.03,
    hr_factor: 1.08,
    f5_factor: 1.02,
  },
  {
    id: '3',
    name: 'Oakland Coliseum',
    team: 'OAK',
    city: 'Oakland',
    lat: 37.7516,
    lng: -122.2005,
    altitude_feet: 13,
    orientation_degrees: 60,
    roof_type: 'open',
    surface: 'grass',
    lf_line_feet: 330,
    rf_line_feet: 330,
    cf_feet: 400,
    run_factor: 0.94,
    hr_factor: 0.89,
    f5_factor: 0.95,
  },
  {
    id: '4',
    name: 'Tropicana Field',
    team: 'TB',
    city: 'St. Petersburg',
    lat: 27.7683,
    lng: -82.6534,
    altitude_feet: 15,
    orientation_degrees: 45,
    roof_type: 'dome',
    surface: 'turf',
    lf_line_feet: 315,
    rf_line_feet: 322,
    cf_feet: 404,
    run_factor: 0.96,
    hr_factor: 0.92,
    f5_factor: 0.97,
  },
  {
    id: '5',
    name: 'Kauffman Stadium',
    team: 'KC',
    city: 'Kansas City',
    lat: 39.0517,
    lng: -94.4803,
    altitude_feet: 886,
    orientation_degrees: 45,
    roof_type: 'open',
    surface: 'grass',
    lf_line_feet: 330,
    rf_line_feet: 330,
    cf_feet: 410,
    run_factor: 0.99,
    hr_factor: 0.90,
    f5_factor: 0.99,
  },
  {
    id: '6',
    name: 'Rogers Centre',
    team: 'TOR',
    city: 'Toronto',
    lat: 43.6414,
    lng: -79.3894,
    altitude_feet: 266,
    orientation_degrees: 0,
    roof_type: 'retractable',
    surface: 'turf',
    lf_line_feet: 328,
    rf_line_feet: 328,
    cf_feet: 400,
    run_factor: 1.02,
    hr_factor: 1.05,
    f5_factor: 1.01,
  },
  {
    id: '7',
    name: 'Progressive Field',
    team: 'CLE',
    city: 'Cleveland',
    lat: 41.4962,
    lng: -81.6852,
    altitude_feet: 660,
    orientation_degrees: 0,
    roof_type: 'open',
    surface: 'grass',
    lf_line_feet: 325,
    rf_line_feet: 325,
    cf_feet: 410,
    run_factor: 0.98,
    hr_factor: 0.99,
    f5_factor: 0.98,
  },
  {
    id: '8',
    name: 'Comerica Park',
    team: 'DET',
    city: 'Detroit',
    lat: 42.339,
    lng: -83.0485,
    altitude_feet: 600,
    orientation_degrees: 150,
    roof_type: 'open',
    surface: 'grass',
    lf_line_feet: 345,
    rf_line_feet: 330,
    cf_feet: 420,
    run_factor: 0.96,
    hr_factor: 0.88,
    f5_factor: 0.96,
  },
  {
    id: '9',
    name: 'Fenway Park',
    team: 'BOS',
    city: 'Boston',
    lat: 42.3467,
    lng: -71.0972,
    altitude_feet: 20,
    orientation_degrees: 45,
    roof_type: 'open',
    surface: 'grass',
    lf_line_feet: 310,
    rf_line_feet: 302,
    cf_feet: 390,
    run_factor: 1.05,
    hr_factor: 0.99,
    f5_factor: 1.05,
  },
  {
    id: '10',
    name: 'Guaranteed Rate Field',
    team: 'CWS',
    city: 'Chicago',
    lat: 41.83,
    lng: -87.6339,
    altitude_feet: 595,
    orientation_degrees: 125,
    roof_type: 'open',
    surface: 'grass',
    lf_line_feet: 330,
    rf_line_feet: 335,
    cf_feet: 400,
    run_factor: 1.02,
    hr_factor: 1.10,
    f5_factor: 1.02,
  },
  {
    id: '11',
    name: 'Target Field',
    team: 'MIN',
    city: 'Minneapolis',
    lat: 44.9818,
    lng: -93.2776,
    altitude_feet: 815,
    orientation_degrees: 90,
    roof_type: 'open',
    surface: 'grass',
    lf_line_feet: 339,
    rf_line_feet: 328,
    cf_feet: 404,
    run_factor: 1.00,
    hr_factor: 1.01,
    f5_factor: 1.00,
  },
  {
    id: '12',
    name: 'Yankee Stadium',
    team: 'NYY',
    city: 'Bronx',
    lat: 40.8296,
    lng: -73.9262,
    altitude_feet: 55,
    orientation_degrees: 75,
    roof_type: 'open',
    surface: 'grass',
    lf_line_feet: 318,
    rf_line_feet: 314,
    cf_feet: 408,
    run_factor: 1.04,
    hr_factor: 1.14,
    f5_factor: 1.03,
  },
  {
    id: '13',
    name: 'Globe Life Field',
    team: 'TEX',
    city: 'Arlington',
    lat: 32.7473,
    lng: -97.0847,
    altitude_feet: 551,
    orientation_degrees: 70,
    roof_type: 'retractable',
    surface: 'grass',
    lf_line_feet: 329,
    rf_line_feet: 326,
    cf_feet: 407,
    run_factor: 1.08,
    hr_factor: 1.04,
    f5_factor: 1.06,
  },
  {
    id: '14',
    name: 'T-Mobile Park',
    team: 'SEA',
    city: 'Seattle',
    lat: 47.5914,
    lng: -122.3325,
    altitude_feet: 17,
    orientation_degrees: 60,
    roof_type: 'retractable',
    surface: 'grass',
    lf_line_feet: 331,
    rf_line_feet: 326,
    cf_feet: 401,
    run_factor: 0.93,
    hr_factor: 0.92,
    f5_factor: 0.94,
  },
  {
    id: '15',
    name: 'Camden Yards',
    team: 'BAL',
    city: 'Baltimore',
    lat: 39.2838,
    lng: -76.6216,
    altitude_feet: 36,
    orientation_degrees: 30,
    roof_type: 'open',
    surface: 'grass',
    lf_line_feet: 334,
    rf_line_feet: 318,
    cf_feet: 410,
    run_factor: 1.02,
    hr_factor: 1.13,
    f5_factor: 1.02,
  },
  {
    id: '16',
    name: 'Truist Park',
    team: 'ATL',
    city: 'Atlanta',
    lat: 33.8908,
    lng: -84.4678,
    altitude_feet: 1050,
    orientation_degrees: 155,
    roof_type: 'open',
    surface: 'grass',
    lf_line_feet: 335,
    rf_line_feet: 325,
    cf_feet: 400,
    run_factor: 1.00,
    hr_factor: 1.01,
    f5_factor: 1.01,
  },
  {
    id: '17',
    name: 'Wrigley Field',
    team: 'CHC',
    city: 'Chicago',
    lat: 41.9484,
    lng: -87.6553,
    altitude_feet: 595,
    orientation_degrees: 45,
    roof_type: 'open',
    surface: 'grass',
    lf_line_feet: 355,
    rf_line_feet: 353,
    cf_feet: 400,
    run_factor: 1.07,
    hr_factor: 1.01,
    f5_factor: 1.05,
  },
  {
    id: '18',
    name: 'Great American Ball Park',
    team: 'CIN',
    city: 'Cincinnati',
    lat: 39.0974,
    lng: -84.5084,
    altitude_feet: 495,
    orientation_degrees: 120,
    roof_type: 'open',
    surface: 'grass',
    lf_line_feet: 328,
    rf_line_feet: 325,
    cf_feet: 404,
    run_factor: 1.13,
    hr_factor: 1.23,
    f5_factor: 1.10,
  },
  {
    id: '19',
    name: 'Coors Field',
    team: 'COL',
    city: 'Denver',
    lat: 39.7559,
    lng: -104.9942,
    altitude_feet: 5280,
    orientation_degrees: 10,
    roof_type: 'open',
    surface: 'grass',
    lf_line_feet: 347,
    rf_line_feet: 350,
    cf_feet: 415,
    run_factor: 1.38,
    hr_factor: 1.18,
    f5_factor: 1.30,
  },
  {
    id: '20',
    name: 'Dodger Stadium',
    team: 'LAD',
    city: 'Los Angeles',
    lat: 34.0739,
    lng: -118.24,
    altitude_feet: 512,
    orientation_degrees: 25,
    roof_type: 'open',
    surface: 'grass',
    lf_line_feet: 330,
    rf_line_feet: 330,
    cf_feet: 395,
    run_factor: 0.94,
    hr_factor: 1.03,
    f5_factor: 0.95,
  },
  {
    id: '21',
    name: 'LoanDepot Park',
    team: 'MIA',
    city: 'Miami',
    lat: 25.7781,
    lng: -80.2196,
    altitude_feet: 10,
    orientation_degrees: 40,
    roof_type: 'retractable',
    surface: 'grass',
    lf_line_feet: 344,
    rf_line_feet: 335,
    cf_feet: 407,
    run_factor: 0.92,
    hr_factor: 0.84,
    f5_factor: 0.93,
  },
  {
    id: '22',
    name: 'American Family Field',
    team: 'MIL',
    city: 'Milwaukee',
    lat: 43.028,
    lng: -87.9712,
    altitude_feet: 635,
    orientation_degrees: 130,
    roof_type: 'retractable',
    surface: 'grass',
    lf_line_feet: 344,
    rf_line_feet: 345,
    cf_feet: 400,
    run_factor: 1.01,
    hr_factor: 1.06,
    f5_factor: 1.01,
  },
  {
    id: '23',
    name: 'Citi Field',
    team: 'NYM',
    city: 'Queens',
    lat: 40.7571,
    lng: -73.8458,
    altitude_feet: 37,
    orientation_degrees: 25,
    roof_type: 'open',
    surface: 'grass',
    lf_line_feet: 335,
    rf_line_feet: 330,
    cf_feet: 408,
    run_factor: 0.95,
    hr_factor: 0.93,
    f5_factor: 0.95,
  },
  {
    id: '24',
    name: 'Citizens Bank Park',
    team: 'PHI',
    city: 'Philadelphia',
    lat: 39.906,
    lng: -75.1665,
    altitude_feet: 20,
    orientation_degrees: 15,
    roof_type: 'open',
    surface: 'grass',
    lf_line_feet: 329,
    rf_line_feet: 330,
    cf_feet: 401,
    run_factor: 1.03,
    hr_factor: 1.13,
    f5_factor: 1.03,
  },
  {
    id: '25',
    name: 'PNC Park',
    team: 'PIT',
    city: 'Pittsburgh',
    lat: 40.4469,
    lng: -80.0057,
    altitude_feet: 730,
    orientation_degrees: 120,
    roof_type: 'open',
    surface: 'grass',
    lf_line_feet: 325,
    rf_line_feet: 320,
    cf_feet: 399,
    run_factor: 0.98,
    hr_factor: 0.88,
    f5_factor: 0.99,
  },
  {
    id: '26',
    name: 'Petco Park',
    team: 'SD',
    city: 'San Diego',
    lat: 32.7073,
    lng: -117.1566,
    altitude_feet: 62,
    orientation_degrees: 0,
    roof_type: 'open',
    surface: 'grass',
    lf_line_feet: 336,
    rf_line_feet: 322,
    cf_feet: 396,
    run_factor: 0.89,
    hr_factor: 0.87,
    f5_factor: 0.90,
  },
  {
    id: '27',
    name: 'Oracle Park',
    team: 'SF',
    city: 'San Francisco',
    lat: 37.7786,
    lng: -122.3893,
    altitude_feet: 12,
    orientation_degrees: 95,
    roof_type: 'open',
    surface: 'grass',
    lf_line_feet: 339,
    rf_line_feet: 309,
    cf_feet: 391,
    run_factor: 0.91,
    hr_factor: 0.79,
    f5_factor: 0.92,
  },
  {
    id: '28',
    name: 'Busch Stadium',
    team: 'STL',
    city: 'St. Louis',
    lat: 38.6226,
    lng: -90.1928,
    altitude_feet: 466,
    orientation_degrees: 60,
    roof_type: 'open',
    surface: 'grass',
    lf_line_feet: 336,
    rf_line_feet: 335,
    cf_feet: 400,
    run_factor: 0.93,
    hr_factor: 0.92,
    f5_factor: 0.94,
  },
  {
    id: '29',
    name: 'Nationals Park',
    team: 'WSH',
    city: 'Washington',
    lat: 38.873,
    lng: -77.0074,
    altitude_feet: 13,
    orientation_degrees: 25,
    roof_type: 'open',
    surface: 'grass',
    lf_line_feet: 336,
    rf_line_feet: 335,
    cf_feet: 402,
    run_factor: 1.01,
    hr_factor: 1.04,
    f5_factor: 1.01,
  },
  {
    id: '30',
    name: 'Chase Field',
    team: 'ARI',
    city: 'Phoenix',
    lat: 33.4453,
    lng: -112.0667,
    altitude_feet: 1100,
    orientation_degrees: 25,
    roof_type: 'retractable',
    surface: 'grass',
    lf_line_feet: 330,
    rf_line_feet: 335,
    cf_feet: 407,
    run_factor: 1.04,
    hr_factor: 1.00,
    f5_factor: 1.03,
  },
]

// Venue lookup by ID, team, or name
const byId = new Map(VENUES.map(v => [v.id, v]))
const byTeam = new Map(VENUES.map(v => [v.team, v]))
const byName = new Map(VENUES.map(v => [v.name.toLowerCase(), v]))

export function getVenueById(id) {
  return byId.get(String(id)) || null
}
export function getVenueByTeam(team) {
  return byTeam.get((team || '').toUpperCase()) || null
}
export function getVenueByName(name) {
  return byName.get((name || '').toLowerCase()) || null
}

/**
 * Resolve by any of the above — useful when the schedule fetcher gives us
 * either a venue id or a team abbreviation.
 */
export function resolveVenue({ id, team, name } = {}) {
  return getVenueById(id) || getVenueByTeam(team) || getVenueByName(name) || null
}
